import type { RobJudgement } from '@/lib/sr/rob/domains';

// ─────────────────────────────────────────────────────────────────────────────
// Report (T18) domain + view types — PURE TYPES, no runtime imports.
//
// The report is GROUNDED: every factual number in the view is computed
// server-side from the review's own recorded data and carries the record set it
// derives from (`ReportSourceId`, rendered as a citation chip). Blinded-derived
// numbers (screening outcomes, RoB roll-ups) are aggregates over every
// reviewer's rows, so they arrive only through the blinding chokepoint and are
// `withheld` while the surface is still `independent` — the DTO carries no
// field that could hold them early.
// ─────────────────────────────────────────────────────────────────────────────

// The record sets a report claim can be grounded in. Every count/statement in
// the view names one — "where this number comes from" is part of the data.
export type ReportSourceId =
  | 'import_ledger'
  | 'screening_records'
  | 'consensus_extraction'
  | 'rob_records'
  | 'team_roster'
  | 'ai_validation'
  | 'review_settings';

export const REPORT_SOURCE_LABEL: Record<ReportSourceId, string> = {
  import_ledger: 'Import ledger',
  screening_records: 'Screening records',
  consensus_extraction: 'Consensus extraction',
  rob_records: 'Risk-of-bias records',
  team_roster: 'Team roster',
  ai_validation: 'AI validation record',
  review_settings: 'Review settings',
};

// One grounded number: computed server-side, never generated by a model.
export interface GroundedCount {
  key: string;
  label: string;
  value: number;
  source: ReportSourceId;
}

// A numbered included-study reference. `citationKey` ('S1', 'S2', …) is what a
// drafted sentence cites; `n` is the rendered [n].
export interface ReportReference {
  citationKey: string;
  n: number;
  studyId: string;
  /** Short label, e.g. "Anker 2021" (authors + year) or the title fallback. */
  label: string;
  title: string;
  journal: string | null;
  year: number | null;
  doi: string | null;
}

// One cell of the characteristics table. `pending` = no consensus recorded yet;
// the other states are the four explicit extraction states — a silent paper
// renders "Not reported", never an invented value and never a blank.
export type CharacteristicCellState =
  'reported' | 'not_reported' | 'na' | 'unclear' | 'pending';

export interface CharacteristicCellDTO {
  value: string | null;
  state: CharacteristicCellState;
}

export interface CharacteristicsRowDTO {
  citationKey: string;
  reference: string;
  design: CharacteristicCellDTO;
  population: CharacteristicCellDTO;
  sampleSize: CharacteristicCellDTO;
  primaryOutcome: CharacteristicCellDTO;
}

// ── Methods · data collection (PRISMA 2020 Items 8 / 9 / 10) ─────────────────
// Every statement is AUTO-assembled from recorded metadata; `recorded` carries
// the exact values the sentence was built from (traceability, testable).
export interface MethodsStatement {
  text: string;
  source: ReportSourceId;
  recorded: Record<string, string | number | boolean | null>;
}

export interface MethodsBlockDTO {
  /** Item 8 — selection process (who screened, independence, automation). */
  selection: MethodsStatement[];
  /** Item 9 — data collection process (who extracted, reconciliation, contact). */
  dataCollection: MethodsStatement[];
  /** Item 10 — data items (what was sought). */
  dataItems: MethodsStatement[];
}

// ── Blinded-derived report sections (chokepoint-gated) ───────────────────────

export interface ScreeningReportSection {
  status: 'available';
  stage: string;
  included: number;
  excluded: number;
  /** Item 16b-shaped per-reason exclusion counts. */
  excludeReasons: Array<{ label: string; count: number }>;
  conflictPending: number;
  inProgress: number;
}

export type RobOverallOutcome = RobJudgement | 'mixed' | 'unassessed';

export interface RobReportSection {
  status: 'available';
  distribution: Array<{
    outcome: RobOverallOutcome;
    label: string;
    count: number;
  }>;
}

// While a surface is `independent` its aggregates are blinded data — the view
// carries a marker, never a number.
export interface WithheldSection {
  status: 'withheld';
}

export type ScreeningSectionDTO = ScreeningReportSection | WithheldSection;
export type RobSectionDTO = RobReportSection | WithheldSection;

// ── Safe pipeline status (completion counts only — chokepoint-safe) ──────────

export interface SurfaceProgressDTO {
  finishedReviewers: number;
  totalReviewers: number;
}

export interface ReportProgressDTO {
  screening: SurfaceProgressDTO;
  extraction: SurfaceProgressDTO;
  rob: SurfaceProgressDTO;
}

export interface ReportPhasesDTO {
  screening: 'independent' | 'reconcile';
  extraction: 'independent' | 'reconcile';
  rob: 'independent' | 'reconcile';
}

// ── AI-drafted prose (labeled + editable — the human owns the text) ──────────

// The ONLY sections the AI may draft. Conclusions / certainty / GRADE are
// deliberately not in this union: the human owns them and no draft path exists.
export type DraftableSectionId = 'abstract' | 'findings';

export interface DraftSentence {
  text: string;
  /** ≥1 grounding citation key ('S1', 'C:identified', …) — enforced. */
  citationKeys: string[];
}

export interface ReportDraftSection {
  id: DraftableSectionId;
  heading: string;
  sentences: DraftSentence[];
}

export interface ReportDraftResult {
  sections: ReportDraftSection[];
  /** Sentences rejected by the grounding gate — surfaced, never silent. */
  droppedSentences: number;
  /** Sections outside the draftable allowlist (e.g. conclusions) — dropped. */
  droppedSections: number;
}

// ── The view the report page hands the client ────────────────────────────────

export interface ReportViewDTO {
  reviewId: string;
  reviewTitle: string;
  reviewType: string;
  reviewMode: 'two_reviewer' | 'ai_co_reviewer';
  /** Caller's live role may trigger an AI draft (owner / collaborator). */
  canDraft: boolean;
  phases: ReportPhasesDTO;
  progress: ReportProgressDTO;
  counts: GroundedCount[];
  screening: ScreeningSectionDTO;
  rob: RobSectionDTO;
  references: ReportReference[];
  characteristics: CharacteristicsRowDTO[];
  methods: MethodsBlockDTO;
}

export type DraftReportActionResult =
  { ok: true; draft: ReportDraftResult } | { ok: false; message: string };
